name: PostToTwitter

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '*/30 * * * *'

on: push #Used for Debug 

jobs:
  test:
    runs-on: macos-latest
    env:
      API_Key: ${{ secrets.API_Key }}
      API_Key_Secret: ${{ secrets.API_Key_Secret }}
      Access_Token: ${{ secrets.Access_Token }}
      Access_Token_Secret: ${{ secrets.Access_Token_Secret }}
    steps:
      - name: "Checkout actions"
        uses: actions/checkout@v1.0.0
      - name: "Check PWD"
        run: pwd
      - name: "Setup Julia action"
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.7.0"
      - name: "Build Julia project"
        uses: julia-actions/julia-buildpkg@master
      - name: "Tun Tweet bot"
        run: julia --project src/TwitterBot.jl ${{ secrets.API_Key }} ${{ secrets.API_Key_Secret }} ${{ secrets.Access_Token }} ${{ secrets.Access_Token_Secret }}
