name: RePostToSlack

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 11 2-30/2 * *' 
    # Runs on all even number days at 11 am UTC! 

# on: push #Used for Debug 

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - run: pwd
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.7.0
      - uses: julia-actions/julia-buildpkg@master
      - run: julia --project src/RePostStackOverflow.jl ${{ secrets.JuliaLangSlackEndPoint }}
        
